<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<script type="text/javascript">
	function showForm(val) {
		if (val == "allac") {
			document.getElementById("block").style.display = "block";
			document.getElementById("block1").style.display = "none";
			document.getElementById("one").style.display = "none";
			document.getElementById("one1").style.display = "none";
		}
		if (val == "oneac") {
			document.getElementById("block").style.display = "none";
			document.getElementById("one").style.display = "block";
			document.getElementById("one1").style.display = "block";
			document.getElementById("block1").style.display = "block";
		}
	}
</script>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Get Your Statement Generated</title>
</head>
<body>
	<c:import url="header.jsp" />
	<h1>Welcome Statement Page</h1>
	<div class="content">
		<div class="container-fluid">
			<div class="row">
				<div class="col-md-12">
					<div class="card">
						<div class="header">
							<h4 class="title">Statment Generated By</h4>
							<p class="category">All the existing user will be displayed
								according to selected display type.</p>
						</div>
						<div class="content">
							<div class="row">
								<div class="col-md-12">
									<center>
										<form name="myform" method="post"
											action="${pageContext.request.contextPath }/ProcessStatement">
											<input type="radio" id="any" name="r" value="allac"
												onclick="showForm(this.value)"> Show All Account
											Details&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio"
												id="accountno" name="r" value="oneac"
												onclick="showForm(this.value)"> Show Details By
											Account Number <BR> <br> <input type="text"
												name="acno" id="one" class="form-control border-input"
												list="data" style="display: none; width: 300px"> <BR>
											<input type="submit" value="Generate Report"
												class="btn btn-info btn-fill btn-wd" style="display: none;"
												id="one1">
											<datalist id="data"> <c:forEach items="${list }"
												var="cus">
												<option
													value="<c:out value="${cus.getAccountNumber() }"></c:out>">
													<c:out value="${cus.getFname() }"></c:out>
													<c:out value="${cus.getLname() }"></c:out>
												</option>
											</c:forEach> </datalist>
										</form>
									</center>
									<div class="content" id="block" style="display: none;">
										<div class="container-fluid">
											<div class="row">
												<div class="col-md-12">
													<div class="card">
														<div class="content table-responsive table-full-width">
															<table class="table table-striped">
																<thead>
																	<th>From Account Number</th>
																	<th>To Account Number</th>
																	<th>Mode</th>
																	<th>Method</th>
																	<th>Date</th>
																	<th>Amount</th>
																	<th>Transferred By</th>
																</thead>
																<tbody>
																	<c:forEach var="c" items="${transfer_list }">
																		<tr>
																			<td><c:out value="${c.getFromAccount() }" /></td>
																			<td><c:out value="${c.getToAccount() }" /></td>
																			<td><c:out value="${c.getMode() }" /></td>
																			<td><c:out value="${c.getMethod() }" /></td>
																			<td><c:out value="${c.getDate() }" /></td>
																			<td><c:out value="${c.getAmount() }" /></td>
																			<td><c:out value="${c.getTransferredBy() }" /></td>
																		<tr>
																	</c:forEach>
																</tbody>
															</table>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
									<c:if test='${transaction.getFromAccount() != "" }' >
										<div class="content" id="block1">
											<div class="container-fluid">
												<div class="row">
													<div class="col-md-12">
														<div class="card">
															<div class="content table-responsive table-full-width">
																<table class="table table-striped">
																	<thead>
																		<th>From Account Number</th>
																		<th>To Account Number</th>
																		<th>Mode</th>
																		<th>Method</th>
																		<th>Date</th>
																		<th>Amount</th>
																		<th>Transferred By</th>
																	</thead>
																	<tbody>
																		<c:forEach var="c" items="${transfer_list }">
																			<c:if test="${transaction.getFromAccount() == c.getFromAccount()}">
																				<tr>
																					<td><c:out value="${c.getFromAccount() }" /></td>
																					<td><c:out value="${c.getToAccount() }" /></td>
																					<td><c:out value="${c.getMode() }" /></td>
																					<td><c:out value="${c.getMethod() }" /></td>
																					<td><c:out value="${c.getDate() }" /></td>
																					<td><c:out value="${c.getAmount() }" /></td>
																					<td><c:out value="${c.getTransferredBy() }" /></td>
																				<tr>
																			</c:if>
																		</c:forEach>
																	</tbody>
																</table>
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
									</c:if>
								</div>
							</div>
							<div class="footer">
								<div class="chart-legend">
									<i class="fa fa-circle text-info"></i> Information <i
										class="fa fa-circle text-danger"></i> Relevant <i
										class="fa fa-circle text-warning"></i> To User Is Displayed
								</div>
								<hr>
								<div class="stats">
									<i class="ti-reload"></i> Updated Every Time You Logged In.
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<c:import url="footer.jsp" />
</body>
</html>